---

language: python
services: docker

env:
  global:
    - ROLE_NAME: easyrsa-ca

install:
  - pip install molecule docker

before_script:
  # Use actual galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME vduseev.$ROLE_NAME
  - cd vduseev.$ROLE_NAME
  # Install galaxy dependencies
  - ansible-galaxy install -p $TRAVIS_BUILD_DIR vduseev.easyrsa

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
